//
//  Recipes.swift
//  PASTArt
//
//  Created by Noah Park on 2022/05/03.
//

import Foundation

let pomodoroRecipes: [RecipeCard] = [
    RecipeCard(id: 0,
               stepName: "준비",
               description: "",
               duration: nil,
               videoName: nil,
               isNoodle: false),
    RecipeCard(id: 1,
               stepName: "면 삶기",
               description: "물에 소금간(1L 당 10g)을 하고 끓으면 파스타 면을 넣고 삶아주세요.\n면 삶기가 끝났다면 불을 끄고 면수는 절대 버리지 말아주세요.",
               duration: nil,
               videoName: "tomatoNoodle",
               isNoodle: true),
    RecipeCard(id: 2,
               stepName: "야채 볶기",
               description: "올리브유를 살짝 두르고 양파가 흐물흐물해질 때까지 중간 불에 볶아주세요.\n어느정도 색이 난다면 마늘과 양송이를 소금 조금과 함께 넣고 볶아주세요.\n타이머가 끝나더라도 흐물흐물하지 않다면 타지 않게 주의하며 계속 볶아줍니다.",
               duration: 240,
               videoName: "fryingOnion",
               isNoodle: false),
    RecipeCard(id: 3,
               stepName: "토마토 퓨레와 함께 볶기",
               description: "불을 약불로 줄이고 토마토 퓨레를 넣어주세요.\n토마토 퓨레의 모든 면이 프라이팬의 밑바닥에 닿게 해주는 것이 중요합니다.\n열은 토마토의 신맛을 날려줘요.\n중간에 파슬리 혹은 바질을 조금 넣어주세요.",
               duration: 240,
               videoName: "tomato",
               isNoodle: false),
    RecipeCard(id: 4,
               stepName: "면수로 농도와 간 맞추기",
               description: "알맞은 간과 농도가 나올 때까지 파스타를 삶은 면수를 넣어주세요.",
               duration: nil,
               videoName: "tomatoMix",
               isNoodle: false),
    RecipeCard(id: 5,
               stepName: "면과 토마토 소스 섞기",
               description: "익은 면과 소스를 함께 볶아주세요.\n너무 걸쭉하다면 면수를 더 넣어주시고, 너무 묽다면 조금 더 볶아주세요.",
               duration: 30,
               videoName: "tomatoMix",
               isNoodle: false),
    RecipeCard(id: 6,
               stepName: "플레이팅",
               description: "예쁘게 플레이팅 합니다.",
               duration: nil,
               videoName: "tomatoPlating",
               isNoodle: false),
]


let alfredoRecipes: [RecipeCard] = [
    RecipeCard(id: 0,
               stepName: "준비",
               description: "",
               duration: nil,
               videoName: nil,
               isNoodle: false),
    RecipeCard(id: 1,
               stepName: "면 삶기",
               description: "물에 소금간(1L 당 10g)을 하고 끓으면 파스타 면을 넣고 삶아주세요.\n면 삶기가 끝났다면 불을 끄고 면수는 절대 버리지 말아주세요.",
               duration: nil,
               videoName: "alfredoNoodle",
               isNoodle: true),
    RecipeCard(id: 2,
               stepName: "베이컨, 야채 볶기",
               description: "올리브유를 살짝 두르고 베이컨을 바삭해질때까지 구워주고, 마늘과 소금 후추를 넣고 볶아줍니다. 어느정도 익으면 브로콜리를 넣어주세요.",
               duration: 240,
               videoName: "alfredoFrying",
               isNoodle: false),
    RecipeCard(id: 3,
               stepName: "생크림과 닭육수 함께 끓이기",
               description: "불을 약불로 줄이고 생크림과 닭육수를 1:1 비율로 넣어주세요\n중간에 파슬리 혹은 바질을 넣어주면 향이 더욱 좋습니다.",
               duration: 240,
               videoName: "alfredoCream",
               isNoodle: false),
    RecipeCard(id: 4,
               stepName: "면수로 농도와 간 맞추기",
               description: "알맞은 간과 농도가 나올 때까지 파스타를 삶은 면수를 넣어주세요.",
               duration: nil,
               videoName: "alfredoMix",
               isNoodle: false),
    RecipeCard(id: 5,
               stepName: "면과 생크림 소스 섞기",
               description: "익은 면과 소스를 함께 볶아주세요.\n너무 걸쭉하다면 면수를 더 넣어주시고, 너무 묽다면 조금 더 볶아주세요.",
               duration: 30,
               videoName: "alfredoMix",
               isNoodle: false),
    RecipeCard(id: 6,
               stepName: "플레이팅",
               description: "예쁘게 플레이팅 합니다.",
               duration: nil,
               videoName: "alfredoPlating",
               isNoodle: false),
]

